-- Run once after creating survey_items.
-- Inserts the initial item pool: 9 Tier 10, 12 Tier 20, 24 Tier 30, and 96 Tier 40 items.

START TRANSACTION;

INSERT INTO survey_items (statement_text, current_tier, notes_internal) VALUES
  ('I feel satisfied with the way things are going in the United States today.', 10, 'Initial Tier 10 seed item.'),
  ('I trust the federal government to act in the public interest.', 10, 'Initial Tier 10 seed item.'),
  ('I believe most people can be trusted.', 10, 'Initial Tier 10 seed item.'),
  ('I feel optimistic about my personal future.', 10, 'Initial Tier 10 seed item.'),
  ('I feel connected to my local community.', 10, 'Initial Tier 10 seed item.'),
  ('I believe the United States is moving in the right direction.', 10, 'Initial Tier 10 seed item.'),
  ('I feel confident about the future of the United States.', 10, 'Initial Tier 10 seed item.'),
  ('I believe people like me have a voice in American society.', 10, 'Initial Tier 10 seed item.'),
  ('I feel hopeful about the next year.', 10, 'Initial Tier 10 seed item.'),

  ('I am satisfied with my current financial situation.', 20, 'Initial Tier 20 seed item.'),
  ('I expect my household financial situation to improve over the next year.', 20, 'Initial Tier 20 seed item.'),
  ('I trust scientists to provide reliable information about important public issues.', 20, 'Initial Tier 20 seed item.'),
  ('I trust journalists to report important events accurately.', 20, 'Initial Tier 20 seed item.'),
  ('I believe elections in the United States are generally administered fairly.', 20, 'Initial Tier 20 seed item.'),
  ('I believe people with different political views can still work together productively.', 20, 'Initial Tier 20 seed item.'),
  ('I feel that my vote matters in national elections.', 20, 'Initial Tier 20 seed item.'),
  ('I believe my local government is responsive to people like me.', 20, 'Initial Tier 20 seed item.'),
  ('I am confident that I can find reliable information when I need it.', 20, 'Initial Tier 20 seed item.'),
  ('I feel safe in the neighborhood where I live.', 20, 'Initial Tier 20 seed item.'),
  ('I believe public schools should receive more funding.', 20, 'Initial Tier 20 seed item.'),
  ('I believe healthcare should be easier for people to access.', 20, 'Initial Tier 20 seed item.'),

  ('I believe climate change is a serious problem.', 30, 'Initial Tier 30 seed item.'),
  ('I believe the government should do more to reduce climate change.', 30, 'Initial Tier 30 seed item.'),
  ('I believe artificial intelligence will improve daily life for most people.', 30, 'Initial Tier 30 seed item.'),
  ('I worry that artificial intelligence will make society less fair.', 30, 'Initial Tier 30 seed item.'),
  ('I believe social media does more harm than good.', 30, 'Initial Tier 30 seed item.'),
  ('I believe people spend too much time looking at screens.', 30, 'Initial Tier 30 seed item.'),
  ('I feel lonely in my everyday life.', 30, 'Initial Tier 30 seed item.'),
  ('I feel that I have people I can rely on when I need help.', 30, 'Initial Tier 30 seed item.'),
  ('I believe hard work is usually rewarded in the United States.', 30, 'Initial Tier 30 seed item.'),
  ('I believe wealth inequality is a serious problem in the United States.', 30, 'Initial Tier 30 seed item.'),
  ('I believe immigration makes the United States stronger.', 30, 'Initial Tier 30 seed item.'),
  ('I believe the legal system treats people fairly.', 30, 'Initial Tier 30 seed item.'),
  ('I believe police officers in my community generally act appropriately.', 30, 'Initial Tier 30 seed item.'),
  ('I believe gun laws should be stricter.', 30, 'Initial Tier 30 seed item.'),
  ('I believe abortion should be legal in most cases.', 30, 'Initial Tier 30 seed item.'),
  ('I believe religion should have more influence in American public life.', 30, 'Initial Tier 30 seed item.'),
  ('I believe universities are a positive force in society.', 30, 'Initial Tier 30 seed item.'),
  ('I believe labor unions are good for workers.', 30, 'Initial Tier 30 seed item.'),
  ('I believe large corporations have too much power.', 30, 'Initial Tier 30 seed item.'),
  ('I believe the economy is working well for people like me.', 30, 'Initial Tier 30 seed item.'),
  ('I believe the United States should play a leading role in world affairs.', 30, 'Initial Tier 30 seed item.'),
  ('I worry about political violence in the United States.', 30, 'Initial Tier 30 seed item.'),
  ('I believe most disagreements can be resolved through respectful conversation.', 30, 'Initial Tier 30 seed item.'),
  ('I believe my life has a clear sense of purpose.', 30, 'Initial Tier 30 seed item.'),

  ('I believe people today are less honest than people were in the past.', 40, 1, 'Initial Tier 40 queue seed item.'),
  ('I believe neighbors should know each other better.', 40, 2, 'Initial Tier 40 queue seed item.'),
  ('I believe remote work has improved life for many workers.', 40, 3, 'Initial Tier 40 queue seed item.'),
  ('I believe remote work has weakened workplace relationships.', 40, 4, 'Initial Tier 40 queue seed item.'),
  ('I believe children today face more pressure than children did in the past.', 40, 5, 'Initial Tier 40 queue seed item.'),
  ('I believe parents should have more control over what schools teach.', 40, 6, 'Initial Tier 40 queue seed item.'),
  ('I believe teachers are respected less than they should be.', 40, 7, 'Initial Tier 40 queue seed item.'),
  ('I believe college is worth the cost for most people.', 40, 8, 'Initial Tier 40 queue seed item.'),
  ('I believe trade schools deserve more respect.', 40, 9, 'Initial Tier 40 queue seed item.'),
  ('I believe student loan debt is a major social problem.', 40, 10, 'Initial Tier 40 queue seed item.'),
  ('I believe housing is too expensive where I live.', 40, 11, 'Initial Tier 40 queue seed item.'),
  ('I believe renting a home is a reasonable long-term choice.', 40, 12, 'Initial Tier 40 queue seed item.'),
  ('I believe home ownership is an important part of financial security.', 40, 13, 'Initial Tier 40 queue seed item.'),
  ('I believe public transportation should be expanded.', 40, 14, 'Initial Tier 40 queue seed item.'),
  ('I believe roads and bridges near me are in good condition.', 40, 15, 'Initial Tier 40 queue seed item.'),
  ('I believe my community is prepared for extreme weather.', 40, 16, 'Initial Tier 40 queue seed item.'),
  ('I believe recycling programs make a meaningful difference.', 40, 17, 'Initial Tier 40 queue seed item.'),
  ('I believe people should eat less meat for environmental reasons.', 40, 18, 'Initial Tier 40 queue seed item.'),
  ('I believe electric vehicles are practical for most drivers.', 40, 19, 'Initial Tier 40 queue seed item.'),
  ('I believe nuclear power should be used more widely.', 40, 20, 'Initial Tier 40 queue seed item.'),
  ('I believe privacy online is still possible.', 40, 21, 'Initial Tier 40 queue seed item.'),
  ('I worry that companies collect too much personal data.', 40, 22, 'Initial Tier 40 queue seed item.'),
  ('I believe the benefits of smartphones outweigh the harms.', 40, 23, 'Initial Tier 40 queue seed item.'),
  ('I believe children should have limited access to smartphones.', 40, 24, 'Initial Tier 40 queue seed item.'),
  ('I believe online dating has made relationships better.', 40, 25, 'Initial Tier 40 queue seed item.'),
  ('I believe people are more isolated because of the internet.', 40, 26, 'Initial Tier 40 queue seed item.'),
  ('I believe misinformation is a major threat to democracy.', 40, 27, 'Initial Tier 40 queue seed item.'),
  ('I believe fact-checking organizations are generally trustworthy.', 40, 28, 'Initial Tier 40 queue seed item.'),
  ('I believe public figures should be held to high standards of personal conduct.', 40, 29, 'Initial Tier 40 queue seed item.'),
  ('I believe political leaders care about ordinary people.', 40, 30, 'Initial Tier 40 queue seed item.'),
  ('I believe compromise in politics is usually a good thing.', 40, 31, 'Initial Tier 40 queue seed item.'),
  ('I believe political parties do more harm than good.', 40, 32, 'Initial Tier 40 queue seed item.'),
  ('I believe voting should be made easier.', 40, 33, 'Initial Tier 40 queue seed item.'),
  ('I believe people should be required to show photo identification to vote.', 40, 34, 'Initial Tier 40 queue seed item.'),
  ('I believe campaign donations give wealthy people too much influence.', 40, 35, 'Initial Tier 40 queue seed item.'),
  ('I believe judges should be more accountable to voters.', 40, 36, 'Initial Tier 40 queue seed item.'),
  ('I believe the Supreme Court is a trustworthy institution.', 40, 37, 'Initial Tier 40 queue seed item.'),
  ('I believe local news is important for democracy.', 40, 38, 'Initial Tier 40 queue seed item.'),
  ('I believe national news focuses too much on conflict.', 40, 39, 'Initial Tier 40 queue seed item.'),
  ('I believe people should pay for high-quality journalism.', 40, 40, 'Initial Tier 40 queue seed item.'),
  ('I believe public libraries are important community institutions.', 40, 41, 'Initial Tier 40 queue seed item.'),
  ('I believe arts and culture deserve public funding.', 40, 42, 'Initial Tier 40 queue seed item.'),
  ('I believe professional sports bring communities together.', 40, 43, 'Initial Tier 40 queue seed item.'),
  ('I believe gambling has become too common in American life.', 40, 44, 'Initial Tier 40 queue seed item.'),
  ('I believe alcohol causes more social harm than people admit.', 40, 45, 'Initial Tier 40 queue seed item.'),
  ('I believe marijuana should be legal for adult use.', 40, 46, 'Initial Tier 40 queue seed item.'),
  ('I believe people should be more careful about what they eat.', 40, 47, 'Initial Tier 40 queue seed item.'),
  ('I believe obesity is mostly caused by social and economic conditions.', 40, 48, 'Initial Tier 40 queue seed item.'),
  ('I believe mental health care should be easier to access.', 40, 49, 'Initial Tier 40 queue seed item.'),
  ('I believe therapy is helpful for most people who try it.', 40, 50, 'Initial Tier 40 queue seed item.'),
  ('I believe people talk openly about mental health more than they used to.', 40, 51, 'Initial Tier 40 queue seed item.'),
  ('I believe Americans are getting enough physical exercise.', 40, 52, 'Initial Tier 40 queue seed item.'),
  ('I believe sleep is undervalued in American culture.', 40, 53, 'Initial Tier 40 queue seed item.'),
  ('I believe people should spend more time outdoors.', 40, 54, 'Initial Tier 40 queue seed item.'),
  ('I believe pets improve people''s quality of life.', 40, 55, 'Initial Tier 40 queue seed item.'),
  ('I believe people should have fewer possessions.', 40, 56, 'Initial Tier 40 queue seed item.'),
  ('I believe buying things online has improved my life.', 40, 57, 'Initial Tier 40 queue seed item.'),
  ('I believe customer service has gotten worse over time.', 40, 58, 'Initial Tier 40 queue seed item.'),
  ('I believe tipping expectations have gone too far.', 40, 59, 'Initial Tier 40 queue seed item.'),
  ('I believe prices are rising faster than wages.', 40, 60, 'Initial Tier 40 queue seed item.'),
  ('I believe it is harder to build a middle-class life than it used to be.', 40, 61, 'Initial Tier 40 queue seed item.'),
  ('I believe people should talk more openly about money.', 40, 62, 'Initial Tier 40 queue seed item.'),
  ('I believe retirement will be financially possible for me.', 40, 63, 'Initial Tier 40 queue seed item.'),
  ('I believe Social Security will be available when I need it.', 40, 64, 'Initial Tier 40 queue seed item.'),
  ('I believe taxes are too complicated.', 40, 65, 'Initial Tier 40 queue seed item.'),
  ('I believe wealthy people should pay more in taxes.', 40, 66, 'Initial Tier 40 queue seed item.'),
  ('I believe small businesses are treated fairly by the government.', 40, 67, 'Initial Tier 40 queue seed item.'),
  ('I believe unions should have more influence in the workplace.', 40, 68, 'Initial Tier 40 queue seed item.'),
  ('I believe people should be able to discuss politics at work.', 40, 69, 'Initial Tier 40 queue seed item.'),
  ('I believe workplace diversity programs are beneficial.', 40, 70, 'Initial Tier 40 queue seed item.'),
  ('I believe men and women have equal opportunities in American society.', 40, 71, 'Initial Tier 40 queue seed item.'),
  ('I believe racism remains a major problem in the United States.', 40, 72, 'Initial Tier 40 queue seed item.'),
  ('I believe people are too quick to take offense.', 40, 73, 'Initial Tier 40 queue seed item.'),
  ('I believe free speech is under threat in the United States.', 40, 74, 'Initial Tier 40 queue seed item.'),
  ('I believe people should be more willing to change their minds.', 40, 75, 'Initial Tier 40 queue seed item.'),
  ('I believe forgiveness is undervalued in public life.', 40, 76, 'Initial Tier 40 queue seed item.'),
  ('I believe patriotism is important.', 40, 77, 'Initial Tier 40 queue seed item.'),
  ('I believe the United States should accept more refugees.', 40, 78, 'Initial Tier 40 queue seed item.'),
  ('I believe border security should be increased.', 40, 79, 'Initial Tier 40 queue seed item.'),
  ('I believe military service deserves more public respect.', 40, 80, 'Initial Tier 40 queue seed item.'),
  ('I believe the United States spends too much on the military.', 40, 81, 'Initial Tier 40 queue seed item.'),
  ('I believe international trade is good for the United States.', 40, 82, 'Initial Tier 40 queue seed item.'),
  ('I believe foreign aid is a good use of public money.', 40, 83, 'Initial Tier 40 queue seed item.'),
  ('I believe space exploration is worth public investment.', 40, 84, 'Initial Tier 40 queue seed item.'),
  ('I believe science fiction helps people imagine better futures.', 40, 85, 'Initial Tier 40 queue seed item.'),
  ('I believe people should read more books.', 40, 86, 'Initial Tier 40 queue seed item.'),
  ('I believe people should learn more history.', 40, 87, 'Initial Tier 40 queue seed item.'),
  ('I believe traditions are important for a healthy society.', 40, 88, 'Initial Tier 40 queue seed item.'),
  ('I believe society changes too quickly.', 40, 89, 'Initial Tier 40 queue seed item.'),
  ('I believe younger generations will make the world better.', 40, 90, 'Initial Tier 40 queue seed item.'),
  ('I believe older generations have valuable wisdom to share.', 40, 91, 'Initial Tier 40 queue seed item.'),
  ('I believe people should volunteer more often.', 40, 92, 'Initial Tier 40 queue seed item.'),
  ('I believe charity can solve many social problems.', 40, 93, 'Initial Tier 40 queue seed item.'),
  ('I believe government programs are necessary to solve many social problems.', 40, 94, 'Initial Tier 40 queue seed item.'),
  ('I believe I can make a positive difference in my community.', 40, 95, 'Initial Tier 40 queue seed item.'),
  ('I believe the future will be better than the present.', 40, 96, 'Initial Tier 40 queue seed item.');

COMMIT;
